name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project_id: studysync-assignments
            secret_name: FIREBASE_SERVICE_ACCOUNTSTUDYSYNC
          - project_id: graphixte
            secret_name: FIREBASE_SERVICE_ACCOUNT_GRAPHIXE
          - project_id: newyork-blogs
            secret_name: FIREBASE_SERVICE_ACCOUNT_NYB
          - project_id: clever-learn
            secret_name: CLEVER_LEARNING
          - project_id: wikipedia-alts
            secret_name: WIKIPEDIA_ALTS
          - project_id: charlie-kirky
            secret_name: KIRKY
          - project_id: redirecting-link
            secret_name: REDIRCTING

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets[matrix.secret_name] }}"
          projectId: "${{ matrix.project_id }}"
          channelId: live
